### PR TITLE
Fix issue #398:Not allowing {fileBasenameNoExtension} 

### LINKED ISSUE #398: Not allowing {fileBasenameNoExtension} to be used in main class launch configuration
When configuring the property, main class in the launch.json file, the extension prevents the predefined ${fileBasenameNoExtension} from being used. The extension keeps saying that it is not a valid class name.  This issue was not present a week prior but now is.
##### Environment
- Operating System: Mac OS Current Version
- JDK version: Current
- Visual Studio Code version: Current
- Java extension version: Current
- Java Debugger extension version: Current

##### Steps To Reproduce
1. Configure a launch.json to have the main class to be a package name then the predefined variable fileBasenameNoExtension
2. Run the program with the configuration

### PR DESCRIPTION
**Pull request by andxu**
Fix #398

### CODE REVIEW

File: src/variableResoler.ts [hunk 1]
```diff
@@ -0,0 +1,232 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
```
Comment (yaohaizh) [inline src/variableResoler.ts]: resoler ==> resolver

File: src/variableResolver.ts [hunk 2]
```diff
@@ -0,0 +1,232 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT license.
```
Comment (yaohaizh) [inline src/variableResolver.ts]: Add a link to the original URI of this file

File: TestPlan.md [hunk 3]
```diff
@@ -437,3 +437,23 @@ Exception in thread "main" java.lang.IllegalStateException
     ```
       Tomcat started on port(s): 8080 (http)
     ```
+
+
```
Comment (yaohaizh) [inline TestPlan.md]: Need update README
