### PR TITLE
fix: correctly parse `ps` output on linux

### LINKED ISSUE #1338: It stopped working the black formater
Type: <b>Bug</b>

It stopped working the black formater

Extension version: 0.50.0
VS Code version: Code 1.77.3 (Universal) (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|17, 14, 14|
|Memory (System)|64.00GB (2.24GB free)|
|Process Argv|--crash-reporter-id 8055bb85-14f3-4c01-88df-d3bcccf618b5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30730054
vsccsb:30705552
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743
9b8hh234:30694863
fixshowwlkth:30730052

```

</details>

### LINKED ISSUE #1388: [BUG]: Cannot find any debuggable program
I run a program by next command line:
```
java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=54583 -jar ./target/cli-0.1.3-jar-with-dependencies.jar
```
as error message suggests:
image

##### Environment
- Operating System: Arch Linux
- JDK version: 17.0.8.1
- Visual Studio Code version: 1.81.1
- Java extension version: v1.21
- Java Debugger extension version: v0.54,0

##### Steps To Reproduce
1. Setup simple maven program. Add next configuration to `.vscode/launch.json`:
```json
    {
      "type": "java",
      "request": "attach",
      "name": "Attach by Process ID",
      "processId": "${command:PickJavaProcess}", // notice this line
    },
```
2. launch java in terminal (external or internal does not metter) with command like from above (`suspend` flag also does not change anything)
3. try launch "Attach by Process ID" configuration

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
[client.log.2023-09-05.log](https://github.com/microsoft/vscode-java-debug/files/12526983/client.log.2023-09-05.log)
[vscode-app-1693937515156.log](https://github.com/microsoft/vscode-java-debug/files/12526987/vscode-app-1693937515156.log)

[Sample project with built java classes](https://github.com/owl-from-hogvarts/vscode-debug-issue)
##### Current Result
Selecting process for debugging by `processId` can't find debuggable process.  
Connection via hostname+port works well. `processId` does not work even if pid number is provided.

##### Expected Result
Selecting process by java process picker or pid works

##### Additional Informations
VScode is installed via `snapd`
Node js and other debuggers works well.

### PR DESCRIPTION
**Pull request by owl-from-hogvarts**
Fixes #1388 

The issue was that `ps`'s output was parsed by hardcoded indexes. The parsing function had been written three years ago. Obviously, ps output format has slightly changed. So I have written regex to parse it more in more flexible fashion. Tested on mine machine. Works grate

### CODE REVIEW

**Comment by owl-from-hogvarts** [comment]
@microsoft-github-policy-service agree

**Comment by owl-from-hogvarts** [comment]
Notice, that checks for existence of `shortName` and `fullCommand` are *not* required. Whole regex does not match if any of these does not.

**Comment by testforstephen** [comment]
@owl-from-hogvarts thanks for your contribution. Since the processTree.ts implementation is originally copied from https://github.com/microsoft/vscode-node-debug/blob/main/src/node/extension/processTree.ts, I'm wondering if updating to the latest version from that source would slove your issue?

**Comment by owl-from-hogvarts** [comment]
Latest version of original file works. But notice, that it uses deprecated `str.substr` method.

**Comment by testforstephen** [comment]
> @testforstephen Latest version of original file works. But notice, that it uses deprecated `str.substr` method.

We can replace the deprecated `substr` with `str.substring(...)`.

**Comment by owl-from-hogvarts** [comment]
Seems meaningful. So, it is now up to you to do code review and choose implementation :wink:

**Comment by owl-from-hogvarts** [comment]
Hey! Who's willing to review this PR?) Two weeks have passed. This still need merge. Just a friendly reminder :wink:

File: src/processTree.ts [hunk 1]
```diff
@@ -128,24 +128,31 @@ export function getProcesses(one: (pid: number, ppid: number, command: string, a
 			proc = spawn('/bin/ps', [ '-ax', '-o', 'pid,ppid,comm:20,command' ]);
 			proc.stdout?.setEncoding('utf8');
 			proc.stdout?.on('data', lines(line => {
+				const PROCESS_REGEX = /^\s*(?<pid>\d+)\s+(?<ppid>\d+)\s+(?<shortName>.+?)\s+(?<fullCommand>.+)$/ium
```
Comment (testforstephen) [inline src/processTree.ts:131]: Since a minor change in the output width can resolve your issue, can we stick to the old approach and apply the following patch? WDYT?
```javascript
            proc = spawn('/bin/ps', [ '-ax', '-o', 'pid:6,ppid:6,comm:20,command' ]);	// we specify the column width explicitly
			proc.stdout.setEncoding('utf8');
			proc.stdout.on('data', lines(line => {

				// the following substr arguments must match the column width specified for the "ps" command above
				const pid = Number(line.substring(0, 6));
				const ppid = Number(line.substr(7, 13));
				let command = line.substring(14, 34).trim();
				let args = line.substring(35);
```

Comment (owl-from-hogvarts) [reply src/processTree.ts:131]: Yeah, we totally can! So, I will apply patch in a couple of hours, may be faster. Though I strongly advocate for preserving this part of patch:
```typescript
let pos = fullCommand.indexOf(shortName);
const commandEndPositionMaybe = fullCommand.indexOf(" ", pos + shortName.length)
const commandEndPosition = commandEndPositionMaybe < 0 ? fullCommand.length : commandEndPositionMaybe;

const command = fullCommand.substring(0, commandEndPosition)
const args = fullCommand.substring(commandEndPosition).trimStart()
```

In my opinion, it facilitates code readability compared to this:
```typescript
let pos = args.indexOf(command);
if (pos >= 0) {
	pos = pos + command.length;
	while (pos < args.length) {
		if (args[pos] === ' ') {
			break;
		}
		pos++;
	}
	command = args.substr(0, pos);
	args = args.substr(pos + 1);
}
```

*Note*: these comments are relevant for both versions
```
// binaries with spaces in path may not work
// possible solution to read directly from /proc
```

File: src/processTree.ts [hunk 2]
```diff
@@ -125,27 +125,25 @@ export function getProcesses(one: (pid: number, ppid: number, command: string, a
...
-							break;
-						}
-						pos++;
-					}
-					command = args.substr(0, pos);
-					args = args.substr(pos + 1);
-				}
+			proc = spawn('/bin/ps', [ '-ax', '-o', 'pid:6,ppid:6,comm:20,command' ]);	// we specify the column width explicitly
+			proc.stdout.setEncoding('utf8');
+			proc.stdout.on('data', lines(line => {
```
Comment (testforstephen) [inline src/processTree.ts:130]: pls keep your change minimum as possible and do not touch irrelevant parts. For example, do not remove `?` from `proc.stdout?.setEncoding` and `proc.stdout?.on`.

File: src/processTree.ts [hunk 3]
```diff
@@ -125,27 +125,25 @@ export function getProcesses(one: (pid: number, ppid: number, command: string, a
...
+				const fullCommand = substr(line, 35)
+
+				// binaries with spaces in path may not work
+				// possible solution to read directly from /proc
+				let pos = fullCommand.indexOf(shortName);
+				const commandEndPositionMaybe = fullCommand.indexOf(" ", pos + shortName.length)
+				const commandEndPosition = commandEndPositionMaybe < 0 ? fullCommand.length : commandEndPositionMaybe;
+
+				const command = fullCommand.substring(0, commandEndPosition)
+				const args = fullCommand.substring(commandEndPosition).trimStart()
```
Comment (testforstephen) [inline src/processTree.ts:146]: You should consider all possible corner cases as possible.

Suggested as below:
```
                let command = shortName;
                let args = fullCommand;
                const pos = fullCommand.indexOf(shortName);
                if (pos >= 0) {
                      const commandEndPositionMaybe = fullCommand.indexOf(" ", pos + shortName.length);
                      const commandEndPosition = commandEndPositionMaybe < 0 ? fullCommand.length : commandEndPositionMaybe;
                      command = fullCommand.substring(0, commandEndPosition)
				      args = fullCommand.substring(commandEndPosition).trimStart()
                }
```

File: src/processTree.ts [hunk 4]
```diff
@@ -157,8 +155,8 @@ export function getProcesses(one: (pid: number, ppid: number, command: string, a
 			reject(err);
 		});
 
-		proc.stderr?.setEncoding('utf8');
-		proc.stderr?.on('data', data => {
+		proc.stderr.setEncoding('utf8');
+		proc.stderr.on('data', data => {
```
Comment (testforstephen) [inline src/processTree.ts:159]: Same as above. Don't remove `?` here.

**Review by testforstephen — CHANGES_REQUESTED** [review]

File: src/processTree.ts (hunk 2 above)
Comment (owl-from-hogvarts) [reply src/processTree.ts:130]: Thank you for review! 

This is not mine change. These are from newest version of node's debugger file. If you check commit history, you'll see that I have taken new file as is. And only on top of that work applied my own.

File: src/processTree.ts (hunk 3 above)
Comment (owl-from-hogvarts) [reply src/processTree.ts]: Although I could not even imagine how this case could ever happen and why not just skip such process, I have incorporated this change into code. Check newly pushed commit

File: src/processTree.ts (hunk 4 above)
Comment (owl-from-hogvarts) [reply src/processTree.ts:164]: You could notice, that updated version of original file uses better typed `ChildProcessWithoutNullStreams` which guarantees that these streams are never null

File: src/processTree.ts [hunk 5]
```diff
@@ -4,10 +4,10 @@
  *
  *  Copied from https://github.com/microsoft/vscode-node-debug/blob/master/src/node/extension/processTree.ts
  *--------------------------------------------------------------------------------------------*/
-/* tslint:disable */
```
Comment (testforstephen) [inline src/processTree.ts:7]: keep this line to skip tslint on this file.

Comment (owl-from-hogvarts) [reply src/processTree.ts:7]: Thank you! Done

**Review by testforstephen — APPROVED** [review]
LGTM. thanks for contribution.
