### PR TITLE
Prompt to add the folder to source path if the running file isn't on classpath

### LINKED ISSUE #470: Disable code lens for the java file not in the project's classpath
image

Hello.java is not in the maven source path `src/main/java`, so jdt will not persist the corresponding .class file in the `target` directory. When the user clicks the Run/Debug code lens, it will pop up `Error: Could not find or load main class Hello`. This sometimes will confuse the user, it's better that the debugger doesn't show the code lens.

### PR DESCRIPTION
**Pull request by testforstephen**
Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>

It requires https://github.com/microsoft/java-debug/pull/302
Close #470

When the Java file isn't on the source path of any project, JDT doesn't build it to .class. Run it via codelens or context menu, the runtime will throw class not found error. One improvement is to provide a fix option to ask user to add the parent folder to Java source path.

### CODE REVIEW

File: src/debugCodeLensProvider.ts [hunk 1]
```diff
@@ -169,9 +170,35 @@ export async function startDebugging(mainClass: string, projectName: string, uri
...
+    if (!parentFsPath) {
+        return true;
+    }
+
+    const parentUri = vscode.Uri.file(parentFsPath);
+    let parentPath = vscode.workspace.asRelativePath(parentUri, true);
+    if (parentPath === parentUri.fsPath) {
+        parentPath = path.basename(parentFsPath);
+    }
+    const ans = await vscode.window.showWarningMessage(`The file ${fileName} isn't on the classpath, the runtime may throw class not found error. `
```
Comment (Eskibear) [inline src/debugCodeLensProvider.ts]: "in" or "on" the classpath?

Comment (testforstephen) [reply src/debugCodeLensProvider.ts]: JDT api called it `isOnClasspath`, i would to keep it consistent.
