### PR TITLE
Disable launcher.bat script to unblock Git Bash users if windows username has blank spaces

### LINKED ISSUE #678: Git bash failed to execute Run/debug when Window username have blank space
##### Environment
- Operating System: Window 7
- JDK version: AdoptOpenJDK 8.0.222.10
- Visual Studio Code version: 1.38.1
- Java extension version: 0.49.0

##### Steps To Reproduce
1. Use git bash as defaut integrated shell
2. Execute run or debug via hover menu.

##### Current Result
```
$ "C:\\Users\\Andree Hai\\.vscode\\extensions\\vscjava.vscode-java-debug-0.22.0\\scripts\\launcher.bat" "C:\\Program Files\\AdoptOpenJDK\\jdk-8
.0.222.10-hotspot\\\\bin\\java" -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:65414 -Dfile.encoding=UTF-8 -cp "C:\\Us
ers\\Andree Hai\\_workspace\\introjava\\assign4\\bin" app.App2
'C:\Users\Andree' is not recognized as an internal or external command,
operable program or batch file.
```

### PR DESCRIPTION
**Pull request by testforstephen**
Fixes #678

### CODE REVIEW

File: src/utility.ts [hunk 1]
```diff
@@ -215,6 +215,18 @@ export function getLauncherScriptPath() {
     return path.join(ext.extensionPath, "scripts", "launcher.bat");
 }
 
+export function isGitBash(isIntegratedTerminal: boolean): boolean {
+    const terminal: vscode.WorkspaceConfiguration = vscode.workspace.getConfiguration("terminal");
```
Comment (Eskibear) [inline src/utility.ts:219]: try vscode's API for current shell?
`const currentWindowsShellPath: string = vscode.env.shell;`

Comment (testforstephen) [reply src/utility.ts]: yes, we can use this API to get current shell for integrated terminal.

**Review by Eskibear — APPROVED** [review]
